name: Android CI(Scene5) v2

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
        add-to-path: true

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      # run: ./gradlew assembleRelease

    - id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"

    - id: find_apk_path
      run: |  
        find . -name "*.apk"
      shell: bash

    - id: apk_path_out
      run: |  
        find . -name "app-release.apk" | awk -F'/' '{print $0}' | head -n 1 | xargs -I {} sh -c '
        PATH_TO_APK="{}"
        cd "$PATH_TO_APK"
        mv app-release.apk app-release-${{ steps.tag.outputs.release_tag }}.apk
        echo "::set-output name=apk_path::$PATH_TO_APK"
        '
      shell: bash
      name: Rename APK

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{ steps.apk_path_out.outputs.apk_path }}/app-release-${{ steps.tag.outputs.release_tag }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
