name: Android CI(Scene5) v2

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
        add-to-path: true

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease --warning-mode all --info
      # ./gradlew build

    - id: tag
      run: |
        tag=$(date +"v%Y-%m-%d-%H-%M")
        echo "Generated release tag: $tag"
        echo "::set-output name=release_tag::$tag"

    - id: print_apk_path
      run: |  
        find ${{ github.workspace }} -name "Scene_*_release.apk"
      shell: bash

    - id: find_apk_path
      run: |  
        echo "::set-output name=apk_path::$(find \${{ github.workspace }} -name "Scene_*_release.apk")"

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{ steps.find_apk_path.outputs.apk_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
